### PR TITLE
Find the Highest Altitude leetcode solution

### PR DESCRIPTION
**Pull request by weberstills**
i have added java solution to a leetocde question for Finding the Highest Altitude, hope it gets merged.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Please add the details [here](https://github.com/Kushal997-das/Hacktoberfest_2021/blob/master/1.%20Beginner%20level/TASK%20%231/data.json)

**Comment by weberstills** [comment]
data.json has been added

**Comment by Kushal997-das** [comment]
> data.json has been added

Add details [here](https://github.com/weberstills/Hacktoberfest_2021/blob/master/1.%20Beginner%20level/TASK%20%231/data.json)
No need to create one more file

**Comment by weberstills** [comment]
data.json added correctly

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Pull request merged**
