### PR TITLE
Added 'The Lead Game' using CPP

### PR DESCRIPTION
**Pull request by Debargha-arch**
- Created a question "The Lead Game" and its solution for TASK 1 and followed further details.
 - Followed TASK 2 as instructed.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Debargha-arch Image URL is not working for the task 2 please check .

**Comment by Debargha-arch** [comment]
Sir, can you tell me where to get the correct image url?

**Comment by Debargha-arch** [comment]
Kindly have a check on the url @Kushal997-das sir.I have updated the link.

**Review by Kushal997-das — APPROVED** [review]
@Debargha-arch LGTM 👍 

@Debargha-arch don't forget  give a star to the repo 👍

**Comment by Debargha-arch** [comment]
Is this project excluded from hacktoberfest?As I am seeing my contribution for this PR showing "Excluded project" in the official hacktoberfest profile even after it getting merged.Kindly reply @Kushal997-das

**Comment by Kushal997-das** [comment]
> Is this project excluded from hacktoberfest?As I am seeing my contribution for this PR showing "Excluded project" in the official hacktoberfest profile even after it getting merged.Kindly reply @Kushal997-das

@Debargha-arch #75

**Pull request merged**
