### PR TITLE
solved the issue "search insert position" in cpp

### PR DESCRIPTION
**Pull request by shalupatidar22**
# Hacktoberfest! 🎊🎈

### 🎉 Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Hacktoberfest-2024/blob/master/CONTRIBUTING.md)? 🤔

(Write your answer here.)

### 📝 Description

(Write your answer here.)

Fixes #issue_no 🔧

### ✅ Checklist

- [x] I've read the contribution guidelines. 📚
- [x] I've checked the issue list before deciding what to submit. 🔍
- [x] I've edited the `README.md` and linked to my code. 📄

## 🔗 Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by shalupatidar22** [comment]
resolved issue using cpp

**Comment by shalupatidar22** [comment]
used cpp to solve the problem search insert positiom

**Comment by shalupatidar22** [comment]
The task is to implement the search insert position functionality in a sorted array. The code should return the index where the target should be inserted to maintain sorted order. If the target is already present in the array, the function should return its current index. The solution should use binary search for an optimal time complexity of O(log n).

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project.
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!

**Pull request closed without merging**
