### PR TITLE
Added  "print matrix in spiral form"

### PR DESCRIPTION
**Pull request by GV-Akhil-Chandra**
Added a new question on how to print a given 2D array in spiral form.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@GV-Akhil-Chandra change the folder name .

**Comment by GV-Akhil-Chandra** [comment]
Can you advice the folder name.

**Comment by Kushal997-das** [comment]
> Can you advice the folder name.

@GV-Akhil-Chandra Your folder name should named as your programming question name .

@GV-Akhil-Chandra don't forget  give a star to the repo 👍

**Comment by GV-Akhil-Chandra** [comment]
@Kushal997-das I am facing some issue with my git, I will close this pr and send a fresh one.

**Pull request closed without merging**
