### PR TITLE
Add my portfolio - Syed Maaz Saeed

### PR DESCRIPTION
**Pull request by syedmaazsaeed**
@Kushal997-das 

Hacktoberfest! 🎊🎈

 🎉 Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Hacktoberfest-2024/blob/master/CONTRIBUTING.md)? 🤔

Yes, I have read the contributing guidelines.

📝 Description :

I have added my portfolio in the `syedmaazsaeed` folder and updated the `data.json` file with my details. I have pushed the code as per the requirements. 

Please check it and merge it into the main branch.

### CODE REVIEW

**Comment by syedmaazsaeed** [comment]
Hi @Kushal997-das

I have contributed to the project through a pull request. Please review it and merge it into the main branch so that it can count towards Hacktoberfest 2024.

Currently, the repository is showing as "excluded" on my Hacktoberfest page.

Could you please let me know why this might be happening?

githubimg

**Comment by syedmaazsaeed** [comment]
Hi @Kushal997-das

I am waiting for Your Response Thanks .

**Comment by Kushal997-das** [comment]
Hi there!

Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!

**Comment by syedmaazsaeed** [comment]
Okay .Thanks

**Pull request closed without merging**
