### PR TITLE
Added problem

### PR DESCRIPTION
**Pull request by jilloestreicher**
Added name to list

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@jilloestreicher Don't add extra files delete the .DS_Store .

@jilloestreicher  don't forget give a star to the repo 👍

**Comment by jilloestreicher** [comment]
Delete .ds_store files and starred, sorry!

**Review by Kushal997-das — APPROVED** [review]
@jilloestreicher 👍

**Comment by jilloestreicher** [comment]
Sorry, but is this project not part of the 2021 Hacktoberfest? It says it is an excluded project on my profile

**Comment by Kushal997-das** [comment]
> Sorry, but is this project not part of the 2021 Hacktoberfest? It says it is an excluded project on my profile

Yes @jilloestreicher This time hacktoberfest strict towards contribution.

**Pull request merged**
