### PR TITLE
Code for Array rotation

### PR DESCRIPTION
**Pull request by ColonelAVP**
Sorry for putting so much PR's. This is my first time in Open-source and I really want to work it out. Thank you.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ColonelAVP It happens don't worry everything looks good except , you didn't add the details in data.json file . Just add deatils in data.json file and send everything in  one PR .

@ColonelAVP don't forget give a star to the repo 👍

**Comment by ColonelAVP** [comment]
I've made the necessary changes. You can check now

**Review by ColonelAVP — COMMENTED** [review]
I've made all the required changes and resolved the conflicts as well. Hope this time it would be approved.

**Review by Kushal997-das — APPROVED** [review]
@ColonelAVP  👍

**Pull request merged**
