### PR TITLE
Added program to find number of repdigits upto n

### PR DESCRIPTION
**Pull request by seikhchilli**
Added program to count the number of repdigits upto n

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@seikhchilli Task #2 is not complete yet .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Yet to completed task #2 and do give a star to the repo 👍

**Comment by seikhchilli** [comment]
I have now completed all the tasks. check it.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Task #2 yet to complete . @seikhchilli

**Pull request closed without merging**
